apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-cjqh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:b655e0ca4ad35193bc4b3e31cda6d0438028913dfd5e8337857e109008d6af2f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
